# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Apuntes de Algoritmos y Programación II
author: Autores
copyright: "2024"
logo: ./contenidos/assets/images/untref-logo-negro.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true
  
parse:
  myst_enable_extensions: 
    - amsmath
    - attrs_inline
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist
    
  

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: apunte.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib
  
sphinx:
  extra_extensions: 
      - sphinx_proof
      - bokeh.sphinxext.bokeh_plot
  config:
    language: es
    bibtex_reference_style: author_year
    proof_minimal_theme: true
